#!/usr/bin/env bash

# Local file setup
readonly program="$(realpath "${0}")"
readonly feeds_dir="$(dirname "$(dirname "${program}")")/Feeds"
readonly feed_file="${feeds_dir}/$(basename "${program}").json"
readonly tmp_file="$(mktemp)"

# Initial feed setup
[[ -f "${feed_file}" ]] || printf '{
  "version": "https://jsonfeed.org/version/1.1",
  "title": "%s",
  "home_page_url": "%s",
  "items": []
}' 'Mr. Lovenstein' 'https://tapas.io/series/MrLovenstein/info' > "${feed_file}"

# Strategy to get feed details
readonly source_url='https://tapas.io/rss/series/3346/'
readonly top_url="$(curl --silent "${source_url}" | xmllint --xpath 'string(/rss/channel/item[1]/link)' -)"
readonly top_id="$(awk -F '/' '{print $NF}' <<< "${top_url}")"
readonly top_contents="$(curl --silent "${top_url}")"
readonly top_title="$(xmllint --html --xpath "string(//*[@id='episode-${top_id}']/div[1]/div/p[1])" - <<< "${top_contents}" 2>/dev/null | sed 's/\?.*//')"
readonly top_media="$(xmllint --html --xpath "string(//*[@id='episode-${top_id}']/div[1]/article/img[1]/@data-src)" - <<< "${top_contents}" 2>/dev/null | sed 's/\?.*//')"
readonly top_bonus="$(xmllint --html --xpath "string(//*[@id='episode-${top_id}']/div[1]/article/img[2]/@data-src)" - <<< "${top_contents}" 2>/dev/null | sed 's/\?.*//')"

# Exit early if item already in feed
[[ "$(jq --raw-output '.items[0].id' "${feed_file}")" == "${top_id}" ]] && exit 0

# Add to feed, keeping only the most recent five
jq \
  --arg id "${top_id}" \
  --arg url "${top_url}" \
  --arg title "${top_title}" \
  --arg html "<img src='${top_media}'><br><img src='${top_bonus}'>" \
  '.items = ([{ id: $id, url: $url, title: $title, content_html: $html }] + (.items // [])) | .items = (.items[0:5])' \
  "${feed_file}" > "${tmp_file}"

mv "${tmp_file}" "${feed_file}"
